"""HTML report generator — produces a comprehensive project report."""

from datetime import datetime
from pathlib import Path
from typing import Optional

from articulate_core.pipeline.models import (
    DeploymentPackage,
    GeneratedCode,
    RequirementDocument,
    SimulationReport,
    StageContext,
    TechnicalApproach,
)


class HTMLReportGenerator:
    """Generates a comprehensive HTML report from pipeline stage outputs."""

    def generate(self, ctx: StageContext, output_path: Optional[Path] = None) -> str:
        """Generate full HTML report."""
        sections = [
            self._header(),
            self._overview(ctx),
            self._requirement_section(ctx.requirement_doc),
            self._approach_section(ctx.technical_approach),
            self._code_section(ctx.generated_code),
            self._simulation_section(ctx.simulation_report),
            self._deployment_section(ctx.deployment_package, ctx.target_brand),
            self._footer(),
        ]
        html = "\n".join(sections)

        if output_path:
            output_path = Path(output_path)
            output_path.parent.mkdir(parents=True, exist_ok=True)
            output_path.write_text(html, encoding="utf-8")

        return html

    @staticmethod
    def _header() -> str:
        return """<!DOCTYPE html>
<html>
<head>
<meta charset="utf-8">
<title>Articulate — Pipeline Report</title>
<style>
  body { font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, sans-serif; margin: 2em; color: #333; }
  h1 { color: #1a1a2e; border-bottom: 3px solid #e94560; padding-bottom: 0.3em; }
  h2 { color: #16213e; margin-top: 1.5em; }
  .section { background: #f8f9fa; border-radius: 8px; padding: 1.2em; margin: 1em 0; }
  .pass { color: #2e7d32; font-weight: bold; }
  .fail { color: #c62828; font-weight: bold; }
  table { border-collapse: collapse; width: 100%; margin: 0.5em 0; }
  th, td { border: 1px solid #ddd; padding: 8px; text-align: left; }
  th { background: #e8eaf6; }
  .metric-pass { background: #e8f5e9; }
  .metric-fail { background: #ffebee; }
  .summary { font-size: 1.1em; padding: 0.5em; border-radius: 4px; }
  pre { background: #263238; color: #eceff1; padding: 1em; border-radius: 4px; overflow-x: auto; }
  code { background: #eceff1; padding: 0.1em 0.3em; border-radius: 3px; }
  .badge { display: inline-block; padding: 0.2em 0.6em; border-radius: 3px; color: #fff; font-size: 0.85em; }
  .badge-pass { background: #2e7d32; }
  .badge-fail { background: #c62828; }
  .badge-skip { background: #f57f17; }
</style>
</head>
<body>
<h1>Articulate Pipeline Report</h1>
"""

    @staticmethod
    def _footer() -> str:
        return f"""
<div class="section">
  <p><em>Generated by Articulate on {datetime.now().strftime('%Y-%m-%d %H:%M')}</em></p>
</div>
</body>
</html>"""

    @staticmethod
    def _overview(ctx: StageContext) -> str:
        passed = []
        if ctx.requirement_doc:
            passed.append("Requirement")
        if ctx.technical_approach:
            passed.append("Technical Approach")
        if ctx.generated_code:
            passed.append("Code Generation")
        if ctx.simulation_report:
            passed.append("Simulation" if ctx.simulation_report.passed else "Simulation (failed)")
        if ctx.deployment_package:
            passed.append("Deployment")

        items = "".join(f"<li>{s}</li>" for s in passed)
        return f"""
<div class="section">
  <h2>Pipeline Overview</h2>
  <p><strong>Project:</strong> {ctx.project_dir.name}</p>
  <p><strong>User Input:</strong> {ctx.user_input or 'N/A'}</p>
  <p><strong>Completed Stages:</strong></p>
  <ul>{items}</ul>
  <p><strong>Target Brand:</strong> {ctx.target_brand.upper() if ctx.target_brand else 'N/A'}</p>
</div>"""

    @staticmethod
    def _requirement_section(req: Optional[RequirementDocument]) -> str:
        if not req:
            return '<div class="section"><h2>Requirement</h2><p class="badge badge-skip">Skipped</p></div>'
        return f"""
<div class="section">
  <h2>Requirement</h2>
  <p><strong>Task Type:</strong> {req.task_type.value}</p>
  <p><strong>Summary:</strong> {req.summary}</p>
  <p><strong>Waypoints:</strong> {len(req.key_waypoints)}</p>
  <p><strong>End Effector:</strong> {req.end_effector or 'N/A'}</p>
</div>"""

    @staticmethod
    def _approach_section(approach: Optional[TechnicalApproach]) -> str:
        if not approach:
            return '<div class="section"><h2>Technical Approach</h2><p class="badge badge-skip">Skipped</p></div>'
        arm = approach.arm_parameters
        n_dof = len(arm.get("dh_params", [])) if arm else 0
        risk_color = {"low": "badge-pass", "medium": "badge-fail", "high": "badge-fail"}.get(
            approach.risk_assessment.level, "badge-skip"
        )
        traj_types = ", ".join(t.value for t in approach.trajectory_types)
        return f"""
<div class="section">
  <h2>Technical Approach</h2>
  <p><strong>DOF:</strong> {n_dof}</p>
  <p><strong>Kinematics:</strong> {approach.kinematics_strategy.method}</p>
  <p><strong>Trajectory Types:</strong> {traj_types}</p>
  <p><strong>Risk Level:</strong> <span class="badge {risk_color}">{approach.risk_assessment.level.upper()}</span></p>
  <p><strong>Description:</strong> {approach.description}</p>
</div>"""

    @staticmethod
    def _code_section(code: Optional[GeneratedCode]) -> str:
        if not code:
            return '<div class="section"><h2>Code Generation</h2><p class="badge badge-skip">Skipped</p></div>'
        files = "".join(
            f"<li><code>{path}</code> ({len(content)} chars)</li>"
            for path, content in sorted(code.package_structure.items())
        )
        return f"""
<div class="section">
  <h2>Code Generation</h2>
  <p><strong>ROS2 Package:</strong> {code.ros2_package_name}</p>
  <p><strong>Files:</strong> {len(code.package_structure)}</p>
  <ul>{files}</ul>
  <p><strong>Build:</strong> <span class="{'pass' if code.build_successful else 'fail'}">{'Success' if code.build_successful else 'N/A'}</span></p>
</div>"""

    @staticmethod
    def _simulation_section(report: Optional[SimulationReport]) -> str:
        if not report:
            return '<div class="section"><h2>Simulation</h2><p class="badge badge-skip">Skipped</p></div>'
        rows = ""
        for name, m in sorted(report.metrics.items()):
            cls = "metric-pass" if m.passed else "metric-fail"
            status = "PASS" if m.passed else "FAIL"
            rows += f"<tr class='{cls}'><td>{name}</td><td>{status}</td><td>{m.value:.4f}</td><td>{m.threshold}</td><td>{m.unit}</td></tr>"
        return f"""
<div class="section">
  <h2>Simulation Validation</h2>
  <p><strong>Overall:</strong> <span class="{'pass' if report.passed else 'fail'}">{'PASS' if report.passed else 'FAIL'}</span></p>
  <p><strong>Pass Rate:</strong> {sum(1 for m in report.metrics.values() if m.passed)}/{len(report.metrics)}</p>
  <table><tr><th>Metric</th><th>Status</th><th>Value</th><th>Threshold</th><th>Unit</th></tr>{rows}</table>
  <p><strong>Repairs:</strong> {len(report.repair_history)}</p>
</div>"""

    @staticmethod
    def _deployment_section(pkg: Optional[DeploymentPackage], brand: str) -> str:
        if not pkg:
            return '<div class="section"><h2>Deployment</h2><p class="badge badge-skip">Skipped</p></div>'
        files = "".join(
            f"<li><code>{name}</code> → {path}</li>" for name, path in sorted(pkg.files.items())
        )
        return f"""
<div class="section">
  <h2>Deployment Package</h2>
  <p><strong>Target Brand:</strong> {brand.upper()}</p>
  <p><strong>Output Directory:</strong> <code>{pkg.output_dir}</code></p>
  <p><strong>Files:</strong></p>
  <ul>{files}</ul>
  <p><strong>Guide:</strong> <a href="file:///{pkg.guide_path}">{pkg.guide_path.name}</a></p>
  <p><strong>Checklist:</strong> <a href="file:///{pkg.checklist_path}">{pkg.checklist_path.name}</a></p>
</div>"""
