# Kinematics parameters
kinematics:
  solver: "kdl"   # KDL, UR, or custom
  position_only: false

  # DH Parameters (standard convention)
  dh_parameters:
    
    joint_0:
      a: 0.0
      alpha: 0.0
      d: 0.0
      theta: 0.0
    
    joint_1:
      a: 0.0
      alpha: 0.0
      d: 0.0
      theta: 0.0
    
    joint_2:
      a: 0.0
      alpha: 0.0
      d: 0.0
      theta: 0.0
    
    joint_3:
      a: 0.0
      alpha: 0.0
      d: 0.0
      theta: 0.0
    
    joint_4:
      a: 0.0
      alpha: 0.0
      d: 0.0
      theta: 0.0
    
    joint_5:
      a: 0.0
      alpha: 0.0
      d: 0.0
      theta: 0.0
    
