"""KUKA KRL (.src + .dat) converter."""

import math
from typing import Dict, List

from articulate_core.skill.converters.base import BaseConverter, Trajectory


class KRLConverter(BaseConverter):
    """Convert trajectories to KUKA KRL (.src + .dat) format."""

    @property
    def brand(self) -> str:
        return "kuka"

    def convert(self, trajectory: Trajectory, output_dir: str) -> Dict[str, str]:
        src_lines = self._generate_src(trajectory)
        dat_lines = self._generate_dat(trajectory)
        return {
            "articulate_program.src": "\n".join(src_lines),
            "articulate_program.dat": "\n".join(dat_lines),
        }

    def _generate_src(self, trajectory: Trajectory) -> List[str]:
        lines = [
            "&ACCESS RVP",
            "&REL 999",
            "&COMMENT Generated by Articulate",
            f"DEF articulate_program( )",
            "",
            f"; Tool: {trajectory.tool_name}",
            f"; Payload: {trajectory.payload_kg} kg",
            f"; Waypoints: {len(trajectory.waypoints)}",
            "",
            "BAS(#INITMOV,0)",
            "",
            "; Configure motion parameters",
            f"$VEL.CP = {trajectory.speed:.3f}",
            f"$ACC.CP = {trajectory.acceleration:.3f}",
            "",
            "; Main motion sequence",
        ]

        for i, wp in enumerate(trajectory.waypoints):
            pos = wp.get("positions", [0.0] * 6)
            wp_type = wp.get("type", "PTP")
            speed = wp.get("speed", trajectory.speed)

            e6pos = self._to_e6pos(pos)
            if wp_type.upper() == "PTP":
                lines.append(f"  ; Waypoint {i + 1}")
                lines.append(f"  $VEL.CP = {speed:.3f}")
                lines.append(f"  PTP {e6pos} C_PTP")
            elif wp_type.upper() == "LIN":
                lines.append(f"  ; Waypoint {i + 1}")
                lines.append(f"  $VEL.CP = {speed:.3f}")
                lines.append(f"  LIN {e6pos} C_DIS")
            elif wp_type.upper() == "CIRC":
                via = wp.get("via", None)
                if via:
                    via_str = self._to_e6pos(via)
                    lines.append(f"  ; Waypoint {i + 1} (circular)")
                    lines.append(f"  CIRC {via_str}, {e6pos} C_DIS")
                else:
                    lines.append(f"  ; Waypoint {i + 1} (circular via not available, using LIN)")
                    lines.append(f"  LIN {e6pos} C_DIS")
            else:
                lines.append(f"  ; Waypoint {i + 1}")
                lines.append(f"  LIN {e6pos} C_DIS")

        lines.extend([
            "",
            "  ; Return to home position",
            "  PTP {A1 0, A2 -90, A3 0, A4 -90, A5 0, A6 0}",
            "",
            "END",
        ])
        return lines

    def _generate_dat(self, trajectory: Trajectory) -> List[str]:
        return [
            "&ACCESS RVP",
            "&REL 999",
            "&COMMENT Generated by Articulate",
            "DEFDAT articulate_program",
            "",
            f"; Tool: {trajectory.tool_name}",
            f"; Payload: {trajectory.payload_kg} kg",
            "",
            "BASISTECH BAS",
            "",
            "INT TOOL_NO = 1",
            "REAL PAYLOAD = {:.2f}".format(trajectory.payload_kg),
            "",
            "ENDDAT",
        ]

    def generate_safety_checklist(self) -> List[str]:
        return [
            "Verify tool frame (TOOL_DATA) matches physical TCP.",
            "Set $OV_PROG to 1% for initial dry-run.",
            "Confirm payload data (LOAD_DATA) is accurate.",
            "Enable all software axis limits.",
            "Test emergency stop circuit before program execution.",
            "Use T1 (reduced velocity) mode for first run.",
            "Ensure KUKA smartPAD enabling switch is functional.",
        ]

    @staticmethod
    def _to_e6pos(values: List[float]) -> str:
        """Format pose as KRL E6POS {A1 .. A6} or {X, Y, Z, A, B, C}."""
        padded = (values + [0.0] * 6)[:6]
        return "{" + ", ".join(f"{v:.4f}" for v in padded) + "}"
