"""ABB RAPID (.mod) converter."""

import math
from typing import Dict, List

from articulate_core.skill.converters.base import BaseConverter, Trajectory


class RAPIDConverter(BaseConverter):
    """Convert trajectories to ABB RAPID (.mod) format."""

    @property
    def brand(self) -> str:
        return "abb"

    def convert(self, trajectory: Trajectory, output_dir: str) -> Dict[str, str]:
        lines = [
            "% Generated by Articulate — ABB RAPID",
            f"% Tool: {trajectory.tool_name}, Payload: {trajectory.payload_kg} kg",
            "",
            "MODULE ArticulateModule",
            "",
            "    ! Data declarations",
            "    PERS tooldata tool:=[TRUE,[[0,0,0],[1,0,0,0]],[{:.3f},[0,0,0],[1,0,0,0,0],0,0,0]];".format(
                trajectory.payload_kg
            ),
            "",
            "    PROC articulate_program()",
            f"        ! Waypoints: {len(trajectory.waypoints)}",
            f"        VelSet {trajectory.speed*1000:.0f}, {trajectory.acceleration*1000:.0f};",
            "",
        ]

        for i, wp in enumerate(trajectory.waypoints):
            pos = wp.get("positions", [0.0] * 6)
            wp_type = wp.get("type", "PTP")
            speed = wp.get("speed", trajectory.speed)
            zone = wp.get("blend", trajectory.blend)
            zone_str = self._zone_to_name(zone)

            robtarget = self._to_robtarget(pos, i + 1)

            lines.append(f"        ! Waypoint {i + 1}")

            if wp_type.upper() == "PTP":
                lines.append(f"        MoveJ {robtarget}, v{speed*1000:.0f}, {zone_str}, tool;")
            elif wp_type.upper() == "LIN":
                lines.append(f"        MoveL {robtarget}, v{speed*1000:.0f}, {zone_str}, tool;")
            elif wp_type.upper() == "CIRC":
                via = wp.get("via", None)
                if via:
                    via_target = self._to_robtarget(via, i + 1, suffix="via")
                    lines.append(f"        MoveC {via_target}, {robtarget}, v{speed*1000:.0f}, {zone_str}, tool;")
                else:
                    lines.append(f"        MoveL {robtarget}, v{speed*1000:.0f}, {zone_str}, tool;")
            else:
                lines.append(f"        MoveL {robtarget}, v{speed*1000:.0f}, {zone_str}, tool;")

            if zone > 0:
                lines.append(f"        ! Blend radius: {zone:.3f} m")

        lines.extend([
            "",
            "        ! Return to home",
            "        MoveJ [[0,0,0],[1,0,0,0],[0,-1,0,0,0,0],[9E9,9E9,9E9,9E9,9E9,9E9]], v500, fine, tool;",
            "    ENDPROC",
            "ENDMODULE",
        ])

        return {"articulate_program.mod": "\n".join(lines)}

    def generate_safety_checklist(self) -> List[str]:
        return [
            "Verify tool data (tooldata) matches physical TCP.",
            "Set system to manual mode (MOTORS ON) before testing.",
            "Confirm payload is within wrist capacity.",
            "Enable axis supervision and software limits.",
            "Test emergency stop before automatic operation.",
            "Run in step-wise mode with reduced speed initially.",
            "Ensure safety zones are correctly configured in the controller.",
        ]

    @staticmethod
    def _to_robtarget(values: List[float], idx: int, suffix: str = "") -> str:
        """Convert pose to ABB robtarget format."""
        padded = (values + [0.0] * 6)[:6]
        return "[[{:.4f},{:.4f},{:.4f}],[1,0,0,0],[0,0,0,0,0,0],[9E9,9E9,9E9,9E9,9E9,9E9]]".format(
            *padded[:3]
        )

    @staticmethod
    def _zone_to_name(blend: float) -> str:
        """Map blend radius to RAPID zone name."""
        if blend <= 0:
            return "fine"
        if blend <= 0.1:
            return "z10"
        if blend <= 0.3:
            return "z30"
        if blend <= 0.5:
            return "z50"
        return "z100"
