"""Universal Robots .script converter."""

import math
from typing import Dict, List

from articulate_core.skill.converters.base import BaseConverter, Trajectory


class URScriptConverter(BaseConverter):
    """Convert trajectories to UR .script (.script) format."""

    @property
    def brand(self) -> str:
        return "ur"

    def convert(self, trajectory: Trajectory, output_dir: str) -> Dict[str, str]:
        lines = [
            "def articulate_program():",
            f'  # Generated by Articulate — {self.brand.upper()} deployment',
            f'  # Waypoints: {len(trajectory.waypoints)}',
            f'  # Tool: {trajectory.tool_name}',
            "",
            "  # Tool configuration",
            f'  set_tool({trajectory.tool_name!r})',
            f"  set_payload({trajectory.payload_kg:.2f})",
            "",
        ]

        for i, wp in enumerate(trajectory.waypoints):
            pos = wp.get("positions", [0.0] * 6)
            wp_type = wp.get("type", "PTP")
            speed = wp.get("speed", trajectory.speed)
            blend = wp.get("blend", trajectory.blend)

            # Ensure 6 values (x, y, z, rx, ry, rz)
            p = self._format_pose(pos)

            if wp_type.upper() == "PTP":
                lines.append(f"  # Waypoint {i + 1}")
                lines.append(f"  movej({p}, a={trajectory.acceleration:.3f}, v={speed:.3f})")
            elif wp_type.upper() == "LIN":
                lines.append(f"  # Waypoint {i + 1}")
                lines.append(f"  movel({p}, a={trajectory.acceleration:.3f}, v={speed:.3f})")
            elif wp_type.upper() == "CIRC":
                lines.append(f"  # Waypoint {i + 1} (circular)")
                # CIRC needs a via point; fall back to movep if none
                via = wp.get("via", None)
                if via:
                    via_str = self._format_pose(via)
                    lines.append(f"  movec({via_str}, {p}, a={trajectory.acceleration:.3f}, v={speed:.3f})")
                else:
                    lines.append(f"  movel({p}, a={trajectory.acceleration:.3f}, v={speed:.3f})")
            else:
                lines.append(f"  # Waypoint {i + 1} (unsupported type {wp_type}, using movel)")
                lines.append(f"  movel({p}, a={trajectory.acceleration:.3f}, v={speed:.3f})")

            if blend > 0:
                lines[-1] = lines[-1].rstrip(")") + f", r={blend:.3f})"

        lines.extend([
            "",
            "  # Return to home",
            '  movej([0.0, -1.57, 0.0, -1.57, 0.0, 0.0], a=1.0, v=0.5)',
            "",
            "end",
        ])

        return {"articulate_program.script": "\n".join(lines)}

    def generate_safety_checklist(self) -> List[str]:
        return [
            "Verify tool TCP calibration before first run.",
            "Set reduced speed mode (250 mm/s) during initial test.",
            "Confirm payload does not exceed wrist rating.",
            "Check joint limit software thresholds are enabled.",
            "Verify emergency stop is functional.",
            "Run program in single-step mode first.",
            "Ensure no personnel inside safeguarded area.",
        ]

    @staticmethod
    def _format_pose(values: List[float]) -> str:
        """Format pose as p[x, y, z, rx, ry, rz]."""
        padded = (values + [0.0] * 6)[:6]
        joined = ", ".join(f"{v:.4f}" for v in padded)
        return f"p[{joined}]"
